# Generated by Django 3.0.6 on 2020-06-24 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qnA', '0011_remove_question_description'),
    ]


    
